filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
before_commands:
    - 'composer install'
tools:
    php_analyzer: true
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: PSR1
    sensiolabs_security_checker: true
    php_loc:
        excluded_dirs:
            - vendor
            - tests
    php_pdepend: true
    php_sim: true
